"""followers

Revision ID: 688742a9d015
Revises: 630e80a6ad3d
Create Date: 2024-01-15 14:03:25.933250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688742a9d015'
down_revision = '630e80a6ad3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
